# Generated by Django 4.2 on 2024-05-31 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Categoriaproducto',
                'verbose_name_plural': 'Categoriaproductos',
                'db_table': 'categoria_producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField(default=0, verbose_name=3)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appFOOD.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('hora_pedido', models.IntegerField()),
                ('direccion_entrega', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField()),
                ('precio_producto', models.FloatField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appFOOD.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appFOOD.producto')),
            ],
            options={
                'verbose_name': 'Detallepedido',
                'verbose_name_plural': 'Detallepedidos',
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
    ]
